import pyautogui as pg
import time

pg.hotkey("win","r")
pg.typewrite("https://www.youtube.com/watch?v=hvKEHcQRM20&t=0s\n")
time.sleep(6)
pg.typewrite("2")
time.sleep(1)
pg.press("right")
pg.hotkey("win","r")
pg.typewrite("notepad\n")
time.sleep(1)
pg.typewrite(".........")
time.sleep(1)
pg.typewrite(".........")
time.sleep(1)
pg.typewrite(".........\n\n")
time.sleep(1)
pg.typewrite("This was a triumph.\n")
time.sleep(3)
pg.typewrite("I'm making a note here\n")
time.sleep(2)
pg.typewrite("huge success.\n\n")
time.sleep(3)
pg.typewrite("It's hard to overstate\n")
time.sleep(2)
pg.typewrite("My satisfaction.\n\n")
time.sleep(5)
pg.typewrite("APERTURE SCIENCE.\n")
time.sleep(4)
pg.typewrite("We do what we must.\n")
time.sleep(1)
pg.typewrite("Because we can.\n")
time.sleep(3)
pg.typewrite("For the good ")
time.sleep(2)
pg.typewrite("of all of us.\n")
time.sleep(2)
pg.typewrite("Except the ones who are dead.\n\n")
time.sleep(2)
pg.typewrite(".........")
time.sleep(1)
pg.typewrite(".........")
time.sleep(1)
pg.typewrite(".........\n\n")